package packet

const (
	WRONG_COUNT            = "WRONG_COUNT"
	EMPTY_PARSE_BUFFER     = "EMPTY_PARSE_BUFFER"
	VALUE_CHILDREN_COEXIST = "VALUE_CHILDREN_COEXIST"
	BUFFER_NOT_EMPTY       = "BUFFER_NOT_EMPTY"
	WRONG_TYPE             = "WRONG_TYPE"
)
