package ndn

const (
	WRONG_COUNT            = "WRONG_COUNT"
	VALUE_CHILDREN_COEXIST = "VALUE_CHILDREN_COEXIST"
	BUFFER_NOT_EMPTY       = "BUFFER_NOT_EMPTY"
	WRONG_TYPE             = "WRONG_TYPE"
	INVALID_SHA_256        = "INVALID_SHA_256"
	INVALID_RSA            = "INVALID_RSA"
	NOT_RSA_PRIVATE_KEY    = "NOT_RSA_PRIVATE_KEY"
	NULL_POINTER           = "NULL_POINTER"
)
