package ndn

const (
	WRONG_COUNT            = "WRONG_COUNT"
	VALUE_CHILDREN_COEXIST = "VALUE_CHILDREN_COEXIST"
	BUFFER_NOT_EMPTY       = "BUFFER_NOT_EMPTY"
	WRONG_TYPE             = "WRONG_TYPE"
	WRONG_SIGNATURE        = "WRONG_SIGNATURE"
	NOT_RSA_PRIVATE_KEY    = "NOT_RSA_PRIVATE_KEY"
)
